


# NOTE WHEN RUNNING IN DEVCONTAINER:
# prefect config set PREFECT_RUNNER_SERVER_HOST=0.0.0.0
# prefect config set PREFECT_API_URL=http://0.0.0.0:4200/api

prefect_server:
	prefect server start


run:
	python3 jg_hw03.py